server {
    listen 80;
    server_name localhost;

    location /admin { alias /usr/share/nginx/html/admin; index index.html; try_files $uri $uri/ /admin/index.html; }
    location /merchant { alias /usr/share/nginx/html/merchant; index index.html; try_files $uri $uri/ /merchant/index.html; }
    location /service { alias /usr/share/nginx/html/service; index index.html; try_files $uri $uri/ /service/index.html; }
    location / { return 301 /admin; }
}
