/**
 * OpenAPI Type Definitions — SaaS Platform v2.0.1
 *
 * Auto-generated by: npm run generate:api
 * (requires backend running on :8012)
 *
 * Manual foundation — will be overwritten by openapi-typescript.
 */

// ===== Shared =====
export interface ApiResponse<T = any> {
  code: number
  msg: string
  data: T
}

export interface PaginatedData<T> {
  items: T[]
  total: number
  page: number
  page_size: number
}

// ===== Auth =====
export interface LoginRequest {
  username: string
  password: string
  merchant_id?: number
}

export interface LoginResponse {
  access_token: string
  refresh_token: string
  token_type: string
  user: {
    id: number
    username: string
    display_name: string
    role: string
    merchant_id: number
  }
}

// ===== Shops =====
export interface ShopCreate {
  platform_type: string
  shop_name: string
  shop_url?: string
}

export interface ShopItem {
  id: number
  platform_type: string
  shop_name: string
  shop_url?: string
  sync_status: string
  last_sync_at?: string
  is_active: number
  product_count: number
  order_count: number
  bind_status: string
  bind_token: string
}

// ===== Products =====
export interface ProductItem {
  id: number
  shop_id: number
  title: string
  price: number
  stock: number
  description?: string
  category_path?: string
  images_json?: string[]
  embedding_status: string
  status: number
}

export interface ProductCreate {
  shop_id: number
  title: string
  price?: number
  stock?: number
  description?: string
  category_path?: string
  status?: number
}

export interface ProductUpdate {
  title?: string
  price?: number
  stock?: number
  description?: string
  category_path?: string
  status?: number
}

export interface SearchResult {
  id: number
  title: string
  price: number
  shop_id: number
  shop_name?: string
  score?: number
}

// ===== Orders =====
export interface OrderItem {
  id: number
  shop_id: number
  platform_order_id: string
  buyer_nick: string
  total_amount: number
  discount_amount?: number
  pay_amount: number
  status: string
  sku_details_json: any[]
  receiver_name?: string
  receiver_phone?: string
  receiver_address?: string
  created_at?: string
}

// ===== Tickets =====
export interface TicketCreate {
  title: string
  description?: string
  priority?: string
  source?: string
  source_id?: number
  category_id?: number
  buyer_openid?: string
  ticket_tags?: string[]
}

export interface TicketItem {
  id: number
  ticket_no: string
  title: string
  priority: string
  status: string
  category_id?: number
  assigned_to?: number
  assignee_name?: string
  sla_breached?: boolean
  created_at?: string
}

export interface TicketStatusUpdate {
  status: string
  resolved_notes?: string
}

export interface TicketCommentCreate {
  content: string
  is_internal?: number
}

// ===== Conversations =====
export interface ConversationItem {
  id: number
  shop_id: number
  buyer_nick: string
  handled_status: string
  assigned_to?: number
  preview: string
  last_message_at?: string
}

export interface ConversationMessageSend {
  content: string
  msg_type?: string
}

// ===== AI =====
export interface AISuggestRequest {
  shop_id: number
  buyer_question: string
  conversation_history?: { role: string; content: string }[]
  product_id?: number
}

export interface AISuggestion {
  content: string
  source: string
  confidence: number
}

// ===== Dashboard =====
export interface DashboardMetrics {
  total_orders: number
  today_orders: number
  pending_conversations: number
  active_shops: number
  ai_adoption_rate: number
  total_tickets: number
  pending_tickets: number
  sla_breached: number
}

// ===== Users =====
export interface UserCreate {
  username: string
  password: string
  display_name?: string
  role: string
}

export interface UserItem {
  id: number
  username: string
  display_name?: string
  role: string
  status: number
}

// ===== KB =====
export interface KbDocumentCreate {
  title: string
  content?: string
  source_type?: string
  source_id?: number
}

// ===== Webhook =====
export interface WebhookLogItem {
  id: number
  event_type: string
  status: string
  response_code?: number
  payload_json?: string
  created_at?: string
}
